version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - sql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "go-course"
    restart: always

volumes:
  sql:
    driver: local